day4/backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduce/', include('introduce.urls')),
    path('coffees/', include('coffees.urls')),
]

day4/fruitdealer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menuboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

day4/intro/intro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from homepage.views import index, fruit, fruit_edit, fruit_new, fruit_delete
urlpatterns = [
    path('', index, name='index'), # 127.0.0.1/
    path('fruit/', fruit, name='fruit'),
    path('fruit_new/', fruit_new, name='fruit_new'),
    path('<int:pk>/fruit_edit/', fruit_edit, name='fruit_edit'),
    path('admin/', admin.site.urls),
    path('<int:pk>/fruit_delete/', fruit_delete, name ='fruit_delete'),
]

day4/menuboard/urls.py
from django.urls import path
from . import views

app_name = 'menuboard'
urlpatterns = [
    path('', views.profile, name="profile"),
    path('fruits/', views.fruit_create_read, name="fruit_create_read"),
    path('fruits/<int:pk>/update/', views.fruit_update, name="fruit_update"),
    path('fruits/<int:pk>/delete/', views.fruit_delete, name="fruit_delete"),
]

day4/menuboard/models.py
from django.db import models

# Create your models here.
class Fruit(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    price = models.IntegerField()
    imgsrc = models.TextField()
    stock = models.IntegerField()

day4/menuboard/forms.py
from django import forms
from .models import Fruit

class FruitForm(forms.ModelForm):
    class Meta:
        model = Fruit
        fields = "__all__"

day4/menuboard/views.py
from django.http.response import JsonResponse
import json
from django.shortcuts import render, redirect
from .models import Fruit
from .forms import FruitForm
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST

# crawling
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.parse import quote

# Create your views here.
@require_GET
def profile(request):
    return render(request, 'menuboard/profile.html')


# fruit Board

# Create, Read
@require_http_methods(['GET', 'POST'])
def fruit_create_read(request):
    # Create
    if request.method == "POST":
        # request.FILES 필수!
        name = quote(request.POST["name"])
        response = urlopen(f'https://terms.naver.com/search.nhn?query={name}')
        soup = BeautifulSoup(response, 'html.parser')
        request_dict = request.POST.dict()
        request_dict['imgsrc'] = soup.select("div.thumb_area img")[0]["data-src"]
        form = FruitForm(request_dict)
        if form.is_valid():
            form.save()
            return redirect('menuboard:fruit_create_read')
    # Read
    fruits = Fruit.objects.all()
    context = {
        'fruits': fruits,
        'create_form': FruitForm(),
    }
    return render(request, 'menuboard/fruitlist.html', context)


# Update
@require_POST
def fruit_update(request, pk):
    # request.body를 json형태로 바꿔줌.
    # request.POST와는 다르게 .dict() 메서드를 사용할 수 없기 때문.
    data = json.loads(request.body.decode('utf-8'))
    print(data)
    fruit = get_object_or_404(Fruit, pk=pk)
    name = quote(data["name"])
    response = urlopen(f'https://terms.naver.com/search.nhn?query={name}')
    soup = BeautifulSoup(response, 'html.parser')
    data['imgsrc'] = soup.select("div.thumb_area img")[0]["data-src"]
    form = FruitForm(data, instance=fruit)
    print(form)
    if form.is_valid():
        form.save()
        return JsonResponse(data)


# Delete
@require_POST
def fruit_delete(request, pk):
    fruit = get_object_or_404(Fruit, pk=pk)
    fruit.delete()
    return redirect('menuboard:fruit_create_read')

day4/menuboard/templates/menuboard/fruitlist.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <h1 class="my-5 text-center">Menu Board</h1>
    <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
            <div class="card h-100 d-flex justify-content-center align-items-center">
                <br>
                <h4>상품 추가하기</h4><br>
                <form action='' method="post">
                    {% csrf_token %}
                    메뉴명: <p>{{ create_form.name }}</p>
                    개당 가격: <p>{{ create_form.price }}</p>
                    재고: <p>{{ create_form.stock }}</p>
                    <button type="submit" class="btn btn-primary btn-sm">등록</button>
                </form>
                <br>
            </div>
        </div>
        {% for fruit in fruits %}
            <div class="col mb-4">
                <div class="card h-100">
                    <img id="fruit-imgsrc-{{ fruit.pk }}" src="{{ fruit.imgsrc }}" class="card-img-top" alt={{ fruit }}>
                    <div id="fruit-{{ fruit.pk }}" class="card-body">
                        <h5 id="fruit-name-{{ fruit.pk }}" class="card-title">{{ fruit.name }}</h5>
                        <input id="fruit-name-{{ fruit.pk }}-input" style="display: none" type="text">
                        <br>
                        가격: <b id="fruit-price-{{ fruit.pk }}">{{ fruit.price }}</b>
                        <input id="fruit-price-{{ fruit.pk }}-input" style="display: none" type="text">원<br>
                        재고: <b id="fruit-stock-{{ fruit.pk }}">{{ fruit.stock }}</b>
                        <input id="fruit-stock-{{ fruit.pk }}-input" style="display: none" type="text">개
                    </div>
                    <div class="d-flex">
                        <form class="ml-3 mb-3" action="{% url 'menuboard:fruit_delete' fruit.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">삭제</button>
                        </form>
                        <form class="ml-3 mb-3 edit-form" data-fruit-id="{{ fruit.pk }}">
                            <button class="btn btn-warning btn-sm">수정</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
    const forms = document.querySelectorAll(".edit-form")

    forms.forEach(function (form) {

        form.addEventListener('submit', function (event) {
            event.preventDefault()
            console.log(event.target.dataset)
            const fruitId = event.target.dataset.fruitId
            const fruitName = document.querySelector(`#fruit-name-${fruitId}`)
            const fruitPrice = document.querySelector(`#fruit-price-${fruitId}`)
            const fruitStock = document.querySelector(`#fruit-stock-${fruitId}`)
            const nameInput = document.querySelector(`#fruit-name-${fruitId}-input`)
            const priceInput = document.querySelector(`#fruit-price-${fruitId}-input`)
            const stockInput = document.querySelector(`#fruit-stock-${fruitId}-input`)

            // 만약 수정버튼에 '수정'이라 쓰여있으면 데이터를 바꿀 수 있는 입력폼으로 변환
            // 수정버튼 누르면 '완료' 버튼으로 바뀜
            if (form.innerText == '수정') {
                
                nameInput.value = fruitName.innerText
                fruitName.style.display = 'none'
                nameInput.style.display = 'inline'

                priceInput.value = fruitPrice.innerText
                fruitPrice.style.display = 'none'
                priceInput.style.display = 'inline'

                stockInput.value = fruitStock.innerText
                fruitStock.style.display = 'none'
                stockInput.style.display = 'inline'

                console.log(form.innerHTML)

                form.innerHTML = '<button class="btn btn-warning btn-sm">완료</button>'

            // 수정버튼에 '완료'라고 쓰여있으면 입력한 데이터를 저장하는 로직 실행
            } else if (form.innerText == '완료') {

                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken').value
                axios.post(`http://127.0.0.1:8000/fruits/${fruitId}/update/`, {
                    // 두 번째 입력칸에는 '전송할 데이터'가 들어감.
                    // 받을때에는 request.POST가 아닌 request.body!!
                    name: nameInput.value,
                    price: priceInput.value,
                    stock: stockInput.value
                }, {
                    headers: {
                        'X-CSRFToken': csrftoken,
                    }
                })
                .then(function (res) {
                    // res.data는 json형태로 받았음.
                    console.log(res.data)

                    fruitName.innerText = res.data.name
                    fruitName.style.display = 'inline'
                    nameInput.style.display = 'none'

                    fruitPrice.innerText = res.data.price
                    fruitPrice.style.display = 'inline'
                    priceInput.style.display = 'none'

                    fruitStock.innerText = res.data.stock
                    fruitStock.style.display = 'inline'
                    stockInput.style.display = 'none'

                    const fruitImgsrc = document.querySelector(`#fruit-imgsrc-${fruitId}`)
                    console.log(fruitImgsrc.src)
                    fruitImgsrc.src = res.data.imgsrc

                    form.innerHTML = '<button class="btn btn-warning btn-sm">수정</button>'
                })
                .catch(function (err) {
                    console.log(err)
                })
            }
        })
    })






    const saves = document.querySelectorAll(".edit-save")

    saves.forEach(function (save) {
        save.addEventListener('submit', function (event) {
            event.preventDefault()
            console.log(event.target.dataset)
            const fruitId = event.target.dataset.fruitId
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken').value

            const fruitName = document.querySelector(`#fruit-name-${fruitId}`)
            const fruitPrice = document.querySelector(`#fruit-price-${fruitId}`)
            const fruitStock = document.querySelector(`#fruit-stock-${fruitId}`)

        })
    })
  </script>
{% endblock content %}

day4/menuboard/templates/menuboard/profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4 text-center">Hello I'm Jinpyo.</h1>
                <figure class="figure">
                    <img src="/media/korea.jpg" class="figure-img img-fluid rounded" alt="...">
                    <figcaption class="figure-caption">A photo in Cheong-Ju.</figcaption>
                </figure>
                <p class="lead">I love korea.</p>
                <p class="lead">I don't speak English.</p>
                <p class="lead">But I want speak English very well.</p>
                <p class="lead">Sometimes I drink coffee.</p>
                <p class="lead">Thank you.</p>
            </div>
        </div>
    </div>
{% endblock content %}